name = "remote-mcp"
main = "src/index.ts"
compatibility_date = "2024-04-07"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "dist"

[env.production]
name = "remote-mcp"
route = ""
workers_dev = true